config/routes.rb
Rails.application.routes.draw do
  get 'photo/destroy'
  resources :discographies
  resources :tours
  resources :artists
  resources :bands
  devise_for :users
  get 'pages/home'
  get 'pages/discography'
  get 'pages/tour'
  get 'pages/contact'
  get 'pages/band'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :name,presence: true
	validates :position,presence: true
	mount_uploader :artist_photo, PhotoUploader

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,except: [:show,:index]
  

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  def saving_images(artist)
    Cloudinary::Uploader.upload("public/uploads/artist/artist_photo/#{artist.id}/#{artist.artist_photo.filename}",public_id:"#{artist.artist_photo.filename}")
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        saving_images(@artist)
        format.html { redirect_to @artist, notice: 'Integrante adicionado.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        saving_images(@artist)
        format.html { redirect_to @artist, notice: 'Integrante Atualizado.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Integrante deletado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :nick_name, :description, :position,:artist_photo)
    end
end

app/views/artists/_form.html.erb
  
<%= simple_form_for @artist do |f| %>
  <% if f.error_notification.present?  %>
    <div class="notification">
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    </div>
  <% end %>
<div class="box">
  <div class="field">
    <label class="label">Nome</label>
    <div class="control">
      <%= f.input :name,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>
  <div class="field">
    <label class="label">Codinome/Apelido</label>
    <div class="control">
      <%= f.input :nick_name,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>
  <div class="field">
    <label class="label">Posição na Banda</label>
    <div class="control">
      <%= f.input :position,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>

  <div class="field">
    <label class="label">Descrição</label>
    <div class="control">
      <%= f.input :description, label: false ,input_html: {class: 'textarea'}%>
    </div>
  </div>

  <div class="field">
    <label class="label">Foto do integrante</label>
      <div class="control">
        <%= f.input :artist_photo,as: :file,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>

  <div class= "control">
    <%= f.button :submit ,class: "button is-primary"%>
  </div>
</div>
<% end %>

app/views/artists/edit.html.erb
&nbsp;
<div class="container">
<article class="message is-dark">
  <div class="message-header">
    <p>Editando o Integrante</p>
</div>
 </article>   
	<%= render 'form', artist: @artist %>
<br>
<%= link_to 'Mostrar', @artist ,class: "button is-link"%> 
<%= link_to 'Voltar', artists_path ,class: "button is-info is-inverted"%>
</div>

app/views/artists/index.html.erb
&nbsp;
<div class="container">
  <p id="notice"><%= notice %></p>

  <% @artists.each do |artist| %>
  <div class="box">
    <article class="media">
      <% if artist.artist_photo.present? %>
        <div class="media-left">
          <figure class="image is-64x64">
            <%= cl_image_tag artist.artist_photo.filename + ".jpg",class: "image is-96x96",secure: true%>
          </figure>
        </div>
      <% end %>
      <div class="media-content">
        <div class="content">
          <p>
            <span class="tag is-black"><%= artist.name %></span> <small>@<%= artist.nick_name %></small> <small></small>
            <br>
            <%= artist.description %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
          <% if current_user.present? %>
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to 'Show', artist ,class: "button is-link"%>
                </p>

                <p class="control">
                  <%= link_to 'Editar', edit_artist_path(artist),class: "button" %>
                </p>
                <p class="control">
                  <%= link_to 'Deletar', artist,class: "button is-danger",method: :delete, data: { confirm: 'Você tem certeza?' } %>
                </p>
              </div>
            <% end %>
          </div>
        </nav>
      </div>
    </article>
  </div>
  <% end %>
  <%= link_to 'Novo artista', new_artist_path,class: "button is-info is-inverted" %>
</div>

app/views/artists/new.html.erb
&nbsp;
<div class="container">
<article class="message is-dark">
  <div class="message-header">
    <p>Cadastrar um novo integrante</p>
</div>
 </article>   
	<%= render 'form', artist: @artist %>
<br>
<%= link_to 'Voltar', artists_path ,class: "button is-info is-inverted"%>
</div>

app/views/artists/show.html.erb
&nbsp;
<% if notice.present? %>
<div class="notification">
	<p id="notice"><%= notice %></p>
</div>
<% end %>
<div class="container">
	<div class="tile is-ancestor">
		<div class="tile is-4 is-vertical is-parent">
			<div class="tile is-child box">
				<p class="title">Nome</p>
				<p><%= @artist.name %></p>
			</div>
			<div class="tile is-child box">
				<p class="title">Nick / Codinome</p>
				<p><%= @artist.nick_name %></p>
			</div>
		</div>
		<div class="tile is-parent">
			<div class="tile is-child box">
				<p class="title">Descrição</p>
				<p><%= @artist.description %></p>
			</div>
		</div>
		<div class="tile is-4 is-vertical is-parent">
			<div class="tile is-child box">
				<% if  @artist.artist_photo.present?%>
				<figure class="image is-4by3"><%= cl_image_tag @artist.artist_photo.filename + ".jpg",secure: true%></figure>
				<% end %>
			</div>
		</div>
	</div>

	<div class="buttons">
		<% if current_user.present? %>
			<%= link_to 'Editar', edit_artist_path(@artist) ,class: "button is-link" %>
		<% end %>
		<%= link_to 'Voltar', artists_path ,class: "button" %>
	</div>
</div>