config/routes.rb
Rails.application.routes.draw do
  get 'photo/destroy'
  resources :discographies
  resources :tours
  resources :artists
  resources :bands
  devise_for :users
  get 'pages/home'
  get 'pages/discography'
  get 'pages/tour'
  get 'pages/contact'
  get 'pages/band'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
	validates :name,presence: true
	validates :description,presence: true
	validates :date_show,presence: true
	mount_uploader :tour_photo, PhotoUploader

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,except: [:show, :index]


  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.order(date_show: :desc).all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  def saving_images(tour)
    Cloudinary::Uploader.upload("public/uploads/tour/tour_photo/#{tour.id}/#{tour.tour_photo.filename}",public_id:"#{tour.tour_photo.filename}")
  end
  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        saving_images(@tour)
        format.html { redirect_to @tour, notice: 'Anúncio de show criado.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        saving_images(@tour)
        format.html { redirect_to @tour, notice: 'Anúncio de show atualizado.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Anúncio de show deletado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name, :date_show, :description,:tour_photo)
    end
end

app/views/tours/_form.html.erb
<%= simple_form_for @tour do |f| %>
  <% if f.error_notification.present?  %>
    <div class="notification">
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    </div>
  <% end %>
<div class="box">
  <div class="field">
    <label class="label">Nome</label>
    <div class="control">
      <%= f.input :name,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>
  <div class="field">
    <label class="label">Data de Lançamento</label>
    <div class="control">
      <%= f.input :date_show,html5: true,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>

  <div class="field">
    <label class="label">Descrição</label>
    <div class="control">
      <%= f.input :description, label: false ,input_html: {class: 'textarea'}%>
    </div>
  </div>

  <div class="field">
    <label class="label">Foto de divulgação do Show</label>
      <div class="control">
        <%= f.input :tour_photo,as: :file,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>

  <div class= "control">
    <%= f.button :submit ,class: "button is-primary"%>
  </div>
</div>
<% end %>

app/views/tours/edit.html.erb
&nbsp;
<div class="container">
	<article class="message is-dark">
	  <div class="message-header">
	    <p>Editando um show</p>
	</div>
	 </article>   
		<%= render 'form', tour: @tour %>
	<br>
	<%= link_to 'Mostrar', @tour ,class: "button is-link"%> 
	<%= link_to 'Voltar', tours_path ,class: "button is-info is-inverted"%>

</div>

app/views/tours/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <% @tours.each do |tour| %>
  <div class="box">
    <article class="media">
      <% if tour.tour_photo.present? %>
        <div class="media-left">
          <figure class="image is-64x64">
            <%= cl_image_tag tour.tour_photo.filename + ".jpg",class: "image is-96x96",secure: true%>
          </figure>
        </div>
      <% end %>
      <div class="media-content">
        <div class="content">
          <p>
            <span class="tag is-black"><%= tour.name %></span> <small>@<%=l tour.date_show %></small> <small></small>
            <br>
            <%= tour.description %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Ver', tour ,target: "_blank",class: "button is-link"%>
              </p>
              <% if current_user.present? %>
                <p class="control">
                  <%= link_to 'Editar', edit_tour_path(tour),class: "button" %>
                </p>
                <p class="control">
                  <%= link_to 'Deletar', tour,class: "button is-danger",method: :delete, data: { confirm: 'Você tem certeza?' } %>
                </p>
              <% end %>
            </div>
          </div>
        </nav>
      </div>
    </article>
  </div>
  <% end %>
  <% if current_user.present? %>
    <%= link_to 'Novo Show', new_tour_path,class: "button is-info is-inverted" %>
  <% end %>
</div>

app/views/tours/new.html.erb
&nbsp;
<div class="container">
	<article class="message is-dark">
		<div class="message-header">
			<p>Cadastrar um novo Show</p>
		</div>
	</article>   
	<%= render 'form', tour: @tour %>
	<br>
	<%= link_to 'Voltar', tours_path ,class: "button is-info is-inverted"%>
</div>

app/views/tours/show.html.erb
<% if notice.present? %>
<div class="notification">
	<p id="notice"><%= notice %></p>
</div>
<% end %>
&nbsp;
<div class="container">
	<div class="tile is-ancestor">
		<div class="tile is-4 is-vertical is-parent">
			<div class="tile is-child box">
				<p class="title">Nome</p>
				<p><%= @tour.name %></p>
			</div>
			<div class="tile is-child box">
				<p class="title">Data do Show</p>
				<p><%=l @tour.date_show %></p>
			</div>
		</div>
		<div class="tile is-parent">
			<div class="tile is-child box">
				<p><%= @tour.description %></p>
			</div>
		</div>
		<div class="tile is-4 is-vertical is-parent">
			<div class="tile is-child box">
				<% if  @tour.tour_photo.present?%>
				<figure class="image is-4by3"><%= cl_image_tag @tour.tour_photo.filename + ".jpg",secure: true%></figure>
				<% end %>
			</div>
		</div>
	</div>

	<div class="buttons">
		<% if current_user.present? %>
			<%= link_to 'Editar', edit_tour_path(@tour) ,class: "button is-link" %>
		<% end %>
		<%= link_to 'Voltar', root_path ,class: "button" %>
	</div>

</div>