config/routes.rb
Rails.application.routes.draw do
  get 'photo/destroy'
  resources :discographies
  resources :tours
  resources :artists
  resources :bands
  devise_for :users
  get 'pages/home'
  get 'pages/discography'
  get 'pages/tour'
  get 'pages/contact'
  get 'pages/band'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discography.rb
class Discography < ApplicationRecord
	validates :name,presence: true
	validates :date_rise,presence: true
	validates :description,presence: true
end

app/controllers/discographies_controller.rb
class DiscographiesController < ApplicationController
  before_action :set_discography, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,except: [:show,:index]

  # GET /discographies
  # GET /discographies.json
  def index
    @discographies = Discography.all
  end

  # GET /discographies/1
  # GET /discographies/1.json
  def show
  end

  # GET /discographies/new
  def new
    @discography = Discography.new
  end

  # GET /discographies/1/edit
  def edit
  end

  # POST /discographies
  # POST /discographies.json
  def create
    @discography = Discography.new(discography_params)

    respond_to do |format|
      if @discography.save
        format.html { redirect_to @discography, notice: 'Discografia Criada.' }
        format.json { render :show, status: :created, location: @discography }
      else
        format.html { render :new }
        format.json { render json: @discography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discographies/1
  # PATCH/PUT /discographies/1.json
  def update
    respond_to do |format|
      if @discography.update(discography_params)
        format.html { redirect_to @discography, notice: 'Discografia Atualizada.' }
        format.json { render :show, status: :ok, location: @discography }
      else
        format.html { render :edit }
        format.json { render json: @discography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discographies/1
  # DELETE /discographies/1.json
  def destroy
    @discography.destroy
    respond_to do |format|
      format.html { redirect_to discographies_url, notice: 'Discografia Deletada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discography
      @discography = Discography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discography_params
      params.require(:discography).permit(:name, :date_rise, :description)
    end
end

app/views/discographies/_form.html.erb
<%= simple_form_for @discography do |f| %>
  <% if f.error_notification.present?  %>
    <div class="notification">
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    </div>
  <% end %>
<div class="box">
  <div class="field">
    <label class="label">Nome</label>
    <div class="control">
      <%= f.input :name,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>
  <div class="field">
    <label class="label">Data de Lançamento</label>
    <div class="control">
      <%= f.input :date_rise,html5: true,label: false ,input_html: {class: 'input'}%>
    </div>
  </div>

  <div class="field">
    <label class="label">Descrição</label>
    <div class="control">
      <%= f.input :description, label: false ,input_html: {class: 'textarea'}%>
    </div>
  </div>
  <div class= "control">
    <%= f.button :submit ,class: "button is-primary"%>
  </div>
</div>
<% end %>

app/views/discographies/edit.html.erb
<div class="container">
	<article class="message is-dark">
	  <div class="message-header">
	    <p>Editando a Música</p>
	</div>
	 </article>   
		<%= render 'form', discography: @discography %>
	<br>
	<%= link_to 'Mostrar', @discography ,class: "button is-link"%> 
	<%= link_to 'Voltar', discographies_path ,class: "button is-info is-inverted"%>
</div>

app/views/discographies/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <article class="message is-dark">
    <div class="message-header">
      <p>Discografia/Músicas</p>
    </div>
  </article>   

  <div class="row columns">

    <% @discographies.each do |discography| %>
    <div class="column">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            <%= discography.name %>
          </p>
          <a href="#" class="card-header-icon" aria-label="more options">
            <span class="icon">
              <i class="fa fa-angle-down" aria-hidden="true"></i>
            </span>
          </a>
        </header>
        <div class="card-content">
          <div class="content">
            <%= link_to discography.description ,target: "_blank" do%>
              <span style="font-size: 48px; color: red;">
                <i class="fa fa-youtube fa-3x"></i>
              </span>
            <% end %>
            <br>
            <p class="title is-4"><%= l discography.date_rise %></p>
          </div>
        </div>
        <footer class="card-footer">
          <% if current_user.present? %>
            <%= link_to 'Ver', discography,class: "card-footer-item button is-link"%>
            <%= link_to 'Editar', edit_discography_path(discography),class: "card-footer-item button" %>
            <%= link_to 'Deletar', discography,class: "card-footer-item button is-danger",method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </footer>
      </div>
    </div>
    <% end %>
  </div>
  &nbsp;
  <% if current_user.present? %>
    <%= link_to 'Nova Discografia', new_discography_path,class: "button is-info is-inverted"  %>
  <% end %>
</div>

app/views/discographies/new.html.erb
<div class="container">
	<article class="message is-dark">
	  <div class="message-header">
	    <p>Cadastrar uma nova Discografia ou Música</p>
	</div>
	 </article>   
		<%= render 'form', discography: @discography %>
	<br>
	<%= link_to 'Voltar', discographies_path ,class: "button is-info is-inverted"%>
</div>

app/views/discographies/show.html.erb
&nbsp;
<p></p>
<% if notice.present? %>
<div class="notification">
	<p id="notice"><%= notice %></p>
</div>
<% end %>
<div class="container">
	<div class="tile is-ancestor">
		<div class="tile is-4 is-vertical is-parent">
			<div class="tile is-child box">
				<p class="title">Nome</p>
				<p><%= @discography.name %></p>
			</div>
			<div class="tile is-child box">
				<p class="title">Data de Lançamento</p>
				<p><%=l @discography.date_rise %></p>
			</div>
		</div>
		<div class="tile is-parent">
			<div class="tile is-child box">
				<p class="title">Letra</p>
					<%= link_to @discography.description do%>
						<span style="font-size: 48px; color: red;">
	                		<i class="fa fa-youtube fa-3x"></i>
						</span>
					<% end %>
			</div>
		</div>
	</div>
	<div class="buttons">
		<% if current_user.present? %>
			<%= link_to 'Editar', edit_discography_path(@discography) ,class: "button is-link" %>
		<% end %>
		<%= link_to 'Voltar', root_path ,class: "button" %>
	</div>
</div>