config/routes.rb
Rails.application.routes.draw do
  get 'photo/destroy'
  resources :discographies
  resources :tours
  resources :artists
  resources :bands
  devise_for :users
  get 'pages/home'
  get 'pages/discography'
  get 'pages/tour'
  get 'pages/contact'
  get 'pages/band'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MalditaVisao</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= favicon_link_tag 'rock.ico', :rel => 'shortcut icon' %>
        <link rel="manifest" href="/manifest.json" />
        <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body class="has-background-dark">
    <nav class="navbar is-dark  is-fixed-top">
        <div class="navbar-brand">
            <%= link_to "Maldita Visão", root_path ,class: "navbar-item" %>
            <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="navbarExampleTransparentExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" id="band_id">
                    Banda
                </a>
                <a class="navbar-item" id="tour_id">
                    Shows
                </a>
                <a class="navbar-item" id="disco_id">
                    Músicas
                </a>
                <a class="navbar-item" id="contact_id">
                    Contato
                </a>
               <% if current_user.present? %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        Mais
                    </a>
                    <div class="navbar-dropdown is-boxed">
                        <%= link_to "Cadastrar Banda", bands_path ,class: "navbar-item" %>
                        <%= link_to "Cadastrar integrantes", artists_path ,class: "navbar-item" %>
                        <%= link_to "Cadastrar discografia", discographies_path ,class: "navbar-item" %>
                        <%= link_to "Cadastrar shows", tours_path ,class: "navbar-item" %>
                    </div>
                </div>
               <% end %>
            </div>
            <div class="navbar-end">
               <% if current_user.present? %>
                   <div class="navbar-item has-dropdown is-hoverable">
                       <%= link_to('Sair'.html_safe,  destroy_user_session_path , method: 'delete',class: 'navbar-link')%>
                   </div>
               <% end %>
            </div>
        </div>
    </nav>
    &nbsp;
    <p></p>

    <section class="section">
        <div class="container has-text-centered">
            <%= yield %>
        </div>
    </section>
    <footer class="footer has-background-dark">
        <div class="container" id="div_contact">
            <div class="content has-text-centered">
                <p>
                    <%= link_to "https://www.facebook.com/Malditavisao/",target: "_blank" do%>
                            <i class="fa fa-facebook-square fa-2x"></i>
                    <% end %>

                    <%= link_to "https://www.instagram.com/malditavisao/?hl=pt-br",target: "_blank" do%>
                            <i class="fa fa-instagram fa-2x"></i>
                    <% end %>

                    <%= link_to "https://www.youtube.com/channel/UC4kTjYiC5FkBUEu8Qdu8tOw",target: "_blank" do%>
                            <i class="fa fa-youtube fa-2x"></i>
                    <% end %>
                </p>
                <p>
                    <a href="https://bulma.io">
                        <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="128" height="24">
                    </a>
                </p>
            </div>
        </div>
    </footer>
</body>


</html>